-- Migración 0008: traducciones al español de títulos y descripciones de productos

ALTER TABLE productos ADD COLUMN titulo_es TEXT;
ALTER TABLE productos ADD COLUMN descripcion_es TEXT;

UPDATE productos SET titulo_es = 'LMNT Electrolitos Zero Azúcar - Sal de Frambuesa | Mezcla para bebida | 30 sobres', descripcion_es = 'LMNT Electrolitos Zero Azúcar - Sal de Frambuesa | Mezcla para bebida | 30 sobres' WHERE asin = 'B07SH31T9V';

UPDATE productos SET titulo_es = 'Nutricost Creatina Monohidrato Micronizada en Polvo 500 g, 100 porciones | 5000 mg por porción (5 g), 17.9 oz', descripcion_es = 'Nutricost Creatina Monohidrato Micronizada en Polvo 500 g, 100 porciones | 5000 mg por porción (5 g), 17.9 oz' WHERE asin = 'B00GL2HMES';

UPDATE productos SET titulo_es = 'Liquid I.V. Hidratación con Electrolitos, Lima Limón, 16 sobres | Formulado científicamente | Hidratación clínicamente probada | Sin edulcorantes artificiales | Sin OGM | Vegano | Mezcla en polvo para bebida', descripcion_es = 'Liquid I.V. Hidratación con Electrolitos, Lima Limón, 16 sobres | Formulado científicamente | Hidratación clínicamente probada | Sin edulcorantes artificiales | Sin OGM | Vegano | Mezcla en polvo para bebida' WHERE asin = 'B01IT9NLHW';

UPDATE productos SET titulo_es = 'Optimum Nutrition Gold Standard Proteína Whey en Polvo, Helado de Vainilla, 2 lb | 24 g de proteína 100% whey por porción, con BCAAs, sin gluten, libre de sustancias prohibidas, fácil mezcla, soporte y recuperación muscular', descripcion_es = 'Optimum Nutrition Gold Standard Proteína Whey en Polvo, Helado de Vainilla, 2 lb | 24 g de proteína 100% whey por porción, con BCAAs, sin gluten, libre de sustancias prohibidas, fácil mezcla, soporte y recuperación muscular' WHERE asin = 'B000GISTZ4';

UPDATE productos SET titulo_es = 'Liquid I.V. Hidratación con Electrolitos sin Azúcar, Lima Limón, 14 sobres | Formulado científicamente | Hidratación clínicamente probada | Cero azúcar | Sin edulcorantes artificiales | Sin OGM | Mezcla en polvo', descripcion_es = 'Liquid I.V. Hidratación con Electrolitos sin Azúcar, Lima Limón, 14 sobres | Formulado científicamente | Hidratación clínicamente probada | Cero azúcar | Sin edulcorantes artificiales | Sin OGM | Mezcla en polvo' WHERE asin = 'B0BQ4G7LY8';

UPDATE productos SET titulo_es = 'Ultima Replenisher Sobres de Electrolitos Original Variety, 20 sobres | Hidratación diaria en polvo sin azúcar con 6 electrolitos y minerales clave - Sin azúcar, a base de plantas y apto para keto', descripcion_es = 'Ultima Replenisher Sobres de Electrolitos Original Variety, 20 sobres | Hidratación diaria en polvo sin azúcar con 6 electrolitos y minerales clave - Sin azúcar, a base de plantas y apto para keto' WHERE asin = 'B08XQZX9K3';

UPDATE productos SET titulo_es = 'THORNE Creatina, Monohidrato de Creatina Micronizada en Polvo, 90 porciones | Favorece la masa muscular magra, la resistencia y la función cognitiva, sin sabor, 5 g por porción, certificado NSF for Sport', descripcion_es = 'THORNE Creatina, Monohidrato de Creatina Micronizada en Polvo, 90 porciones | Favorece la masa muscular magra, la resistencia y la función cognitiva, sin sabor, 5 g por porción, certificado NSF for Sport' WHERE asin = 'B07978VPPH';

UPDATE productos SET titulo_es = 'Optimum Nutrition Creatina Monohidrato en Polvo, sin sabor, 10 oz | 5 g de creatina monohidrato micronizada por porción, favorece la fuerza y potencia muscular, fácil mezcla, libre de sustancias prohibidas', descripcion_es = 'Optimum Nutrition Creatina Monohidrato en Polvo, sin sabor, 10 oz | 5 g de creatina monohidrato micronizada por porción, favorece la fuerza y potencia muscular, fácil mezcla, libre de sustancias prohibidas' WHERE asin = 'B002DYIZEE';

UPDATE productos SET titulo_es = 'Orgain Proteína en Polvo Vegana Orgánica 21 g, Vainilla, 2.03 lb | Proteína a base de plantas, 4 g de fibra prebiótica, sin azúcar añadido ni lactosa, sin OGM, para batidos y smoothies', descripcion_es = 'Orgain Proteína en Polvo Vegana Orgánica 21 g, Vainilla, 2.03 lb | Proteína a base de plantas, 4 g de fibra prebiótica, sin azúcar añadido ni lactosa, sin OGM, para batidos y smoothies' WHERE asin = 'B00J074W7Q';

UPDATE productos SET titulo_es = 'Quest Nutrition Chips de Proteína Estilo Tortilla Sabor Nacho Queso, 12 unidades | 18 g de proteína, 4 g de carbohidratos netos, sin gluten, horneados, sabor queso cheddar cremoso y nacho queso, bolsas individuales de 1.1 oz', descripcion_es = 'Quest Nutrition Chips de Proteína Estilo Tortilla Sabor Nacho Queso, 12 unidades | 18 g de proteína, 4 g de carbohidratos netos, sin gluten, horneados, sabor queso cheddar cremoso y nacho queso, bolsas individuales de 1.1 oz' WHERE asin = 'B07RRRV5CT';

UPDATE productos SET titulo_es = 'Ensure Max Batido de Proteína Chocolate con Leche, 30 g de proteína, 12 unidades | 30 g de proteína para favorecer la salud muscular y controlar el hambre en adultos, cada batido tiene 1 g de azúcar, 150 calorías y 4 g de fibra', descripcion_es = 'Ensure Max Batido de Proteína Chocolate con Leche, 30 g de proteína, 12 unidades | 30 g de proteína para favorecer la salud muscular y controlar el hambre en adultos, cada batido tiene 1 g de azúcar, 150 calorías y 4 g de fibra' WHERE asin = 'B0791Y2LMB';

UPDATE productos SET titulo_es = 'Dymatize ISO100 Proteína en Polvo, 100% Aislado de Whey, Vainilla Gourmet | 25 g de proteína, hidrolizada, de rápida absorción, favorece la salud muscular, 5.5 g de BCAAs, sin gluten, 20 porciones, 1.3 lb', descripcion_es = 'Dymatize ISO100 Proteína en Polvo, 100% Aislado de Whey, Vainilla Gourmet | 25 g de proteína, hidrolizada, de rápida absorción, favorece la salud muscular, 5.5 g de BCAAs, sin gluten, 20 porciones, 1.3 lb' WHERE asin = 'B099J2SWXV';

UPDATE productos SET titulo_es = 'Optimum Nutrition Creatina Monohidrato Micronizada en Cápsulas, 100 unidades | Cápsulas de creatina monohidrato micronizada, fáciles de tragar, aptas para keto, favorecen el desarrollo muscular, la fuerza y el rendimiento', descripcion_es = 'Optimum Nutrition Creatina Monohidrato Micronizada en Cápsulas, 100 unidades | Cápsulas de creatina monohidrato micronizada, fáciles de tragar, aptas para keto, favorecen el desarrollo muscular, la fuerza y el rendimiento' WHERE asin = 'B00DLWONF2';

UPDATE productos SET titulo_es = 'Premier Protein Proteína en Polvo 30 g de proteína, 100% Whey, Vainilla, 17 porciones | Sin azúcar añadido, favorece la salud muscular, sin soja y sin gluten, 1.5 lb', descripcion_es = 'Premier Protein Proteína en Polvo 30 g de proteína, 100% Whey, Vainilla, 17 porciones | Sin azúcar añadido, favorece la salud muscular, sin soja y sin gluten, 1.5 lb' WHERE asin = 'B06ZZ3PJQD';

UPDATE productos SET titulo_es = 'Create Gomitas de Creatina Monohidrato para Hombres y Mujeres, mejoran el enfoque, la fuerza y la resistencia, fórmula antiderretimiento, veganas, sin gluten, sin OGM, 1.5 g de creatina por gomita (Naranja)', descripcion_es = 'Create Gomitas de Creatina Monohidrato para Hombres y Mujeres, mejoran el enfoque, la fuerza y la resistencia, fórmula antiderretimiento, veganas, sin gluten, sin OGM, 1.5 g de creatina por gomita (Naranja)' WHERE asin = 'B0CJH5RWPD';

UPDATE productos SET titulo_es = 'Nuun Sport Tabletas de Electrolitos con Magnesio, Calcio, Potasio, Cloruro y Sodio, sin gluten y veganas, sabores variados, 6 tubos (60 porciones en total)', descripcion_es = 'Nuun Sport Tabletas de Electrolitos con Magnesio, Calcio, Potasio, Cloruro y Sodio, sin gluten y veganas, sabores variados, 6 tubos (60 porciones en total)' WHERE asin = 'B01AMVB87A';

UPDATE productos SET titulo_es = 'REDMOND Re-Lyte Mezcla de Electrolitos en Polvo sin Azúcar (Fresa con Limonada) | Electrolitos cero azúcar, polvo de hidratación', descripcion_es = 'REDMOND Re-Lyte Mezcla de Electrolitos en Polvo sin Azúcar (Fresa con Limonada) | Electrolitos cero azúcar, polvo de hidratación' WHERE asin = 'B097QF7HVH';

UPDATE productos SET titulo_es = 'Transparent Labs Proteína Whey de Vaca Alimentada con Pasto - 30 porciones, Vainilla Francesa | Saborizada naturalmente, proteína en polvo sin gluten con 28 g de proteína por porción y 9 aminoácidos', descripcion_es = 'Transparent Labs Proteína Whey de Vaca Alimentada con Pasto - 30 porciones, Vainilla Francesa | Saborizada naturalmente, proteína en polvo sin gluten con 28 g de proteína por porción y 9 aminoácidos' WHERE asin = 'B0CQ3JTR6F';

UPDATE productos SET titulo_es = 'Nectar Sobres de Hidratación - Sobres de Electrolitos en Polvo - Sin azúcar y 0 calorías - Electrolitos diarios IV de fruta orgánica para aliviar y recuperar la hidratación (Variedad 30 sobres)', descripcion_es = 'Nectar Sobres de Hidratación - Sobres de Electrolitos en Polvo - Sin azúcar y 0 calorías - Electrolitos diarios IV de fruta orgánica para aliviar y recuperar la hidratación (Variedad 30 sobres)' WHERE asin = 'B09BD8GZ8L';

UPDATE productos SET titulo_es = 'Liquid I.V. Sobres de Electrolitos sin Azúcar, Paquete Variedad Clásico, 16 sobres | Formulado científicamente | Hidratación clínicamente probada | Cero azúcar | Sin edulcorantes artificiales | Sin OGM | Mezcla en polvo', descripcion_es = 'Liquid I.V. Sobres de Electrolitos sin Azúcar, Paquete Variedad Clásico, 16 sobres | Formulado científicamente | Hidratación clínicamente probada | Cero azúcar | Sin edulcorantes artificiales | Sin OGM | Mezcla en polvo' WHERE asin = 'B0CSQWZPBX';

UPDATE productos SET titulo_es = 'TREVI Sobres de Electrolitos en Polvo, Hidratación sin Azúcar, Favoritos 20 unidades | Mezcla diaria esencial, 0 azúcar, magnesio, potasio, vitamina C, calcio y vitaminas B6 y B12', descripcion_es = 'TREVI Sobres de Electrolitos en Polvo, Hidratación sin Azúcar, Favoritos 20 unidades | Mezcla diaria esencial, 0 azúcar, magnesio, potasio, vitamina C, calcio y vitaminas B6 y B12' WHERE asin = 'B0GT1GCSTQ';

UPDATE productos SET titulo_es = 'VELOMIX Set de 2 Botellas Batidora de Proteína de 28 oz, Negro/Transparente | Con 2 batidores de alambre, vasos a prueba de fugas para batidos de proteína, apilables, aptos para lavavajillas, sin BPA, listos para preentrenos y fitness', descripcion_es = 'VELOMIX Set de 2 Botellas Batidora de Proteína de 28 oz, Negro/Transparente | Con 2 batidores de alambre, vasos a prueba de fugas para batidos de proteína, apilables, aptos para lavavajillas, sin BPA, listos para preentrenos y fitness' WHERE asin = 'B0CXPWMSX6';

UPDATE productos SET titulo_es = 'NAKED Whey Proteína Whey 100% de Vaca Alimentada con Pasto, 2 lb - Solo 1 ingrediente, proteína whey sin sabor, certificada NSF, no desnaturalizada, sin gluten, sin soja, sin OGM, sin conservantes', descripcion_es = 'NAKED Whey Proteína Whey 100% de Vaca Alimentada con Pasto, 2 lb - Solo 1 ingrediente, proteína whey sin sabor, certificada NSF, no desnaturalizada, sin gluten, sin soja, sin OGM, sin conservantes' WHERE asin = 'B00XIKPUK4';

UPDATE productos SET titulo_es = 'Optimum Nutrition Amino Energy en Polvo, Sandía, 1 lb | Energía en polvo para cualquier momento con BCAAs, aminoácidos y cafeína de té verde y granos de café, apto para keto, soporte a la recuperación muscular', descripcion_es = 'Optimum Nutrition Amino Energy en Polvo, Sandía, 1 lb | Energía en polvo para cualquier momento con BCAAs, aminoácidos y cafeína de té verde y granos de café, apto para keto, soporte a la recuperación muscular' WHERE asin = 'B00GY5E39Y';

UPDATE productos SET titulo_es = 'Momentous Creatina Monohidrato en Polvo, 5 g por porción, sin sabor | Favorece la masa muscular magra, la fuerza, la recuperación y la función cognitiva, certificada NSF for Sport, sin OGM y sin gluten (90 porciones)', descripcion_es = 'Momentous Creatina Monohidrato en Polvo, 5 g por porción, sin sabor | Favorece la masa muscular magra, la fuerza, la recuperación y la función cognitiva, certificada NSF for Sport, sin OGM y sin gluten (90 porciones)' WHERE asin = 'B085Z9P87K';

UPDATE productos SET titulo_es = 'Cure Hydration - Polvo de bebida con electrolitos Fresa Kiwi, 14 sobres | Mezcla a base de plantas para aliviar la deshidratación, hecha con agua de coco, sin azúcar añadido, vegana, sin OGM, sin gluten, elegible FSA-HSA', descripcion_es = 'Cure Hydration - Polvo de bebida con electrolitos Fresa Kiwi, 14 sobres | Mezcla a base de plantas para aliviar la deshidratación, hecha con agua de coco, sin azúcar añadido, vegana, sin OGM, sin gluten, elegible FSA-HSA' WHERE asin = 'B0BRRRKDK5';

UPDATE productos SET titulo_es = 'NAKED Pure Creatina Monohidrato Micronizada en Polvo - Certificada NSF, sin sabor, 500 g, 1.1 lb - Vegana, sin OGM, sin gluten, sin soja, sin rellenos, favorece el crecimiento y la fuerza muscular - 100 porciones', descripcion_es = 'NAKED Pure Creatina Monohidrato Micronizada en Polvo - Certificada NSF, sin sabor, 500 g, 1.1 lb - Vegana, sin OGM, sin gluten, sin soja, sin rellenos, favorece el crecimiento y la fuerza muscular - 100 porciones' WHERE asin = 'B0B9YMNYWK';

UPDATE productos SET titulo_es = 'Quest Nutrition Paquete Variedad de Chips de Proteína, 19 g de proteína, 12 unidades | BBQ, Queso Cheddar y Crema Agria, Crema Agria y Cebolla, 4 de cada sabor, 19 g de proteína, 4 g de carbohidratos netos, horneados, bolsas de 1.1 oz, 12 unidades', descripcion_es = 'Quest Nutrition Paquete Variedad de Chips de Proteína, 19 g de proteína, 12 unidades | BBQ, Queso Cheddar y Crema Agria, Crema Agria y Cebolla, 4 de cada sabor, 19 g de proteína, 4 g de carbohidratos netos, horneados, bolsas de 1.1 oz, 12 unidades' WHERE asin = 'B09WCWK8LM';

UPDATE productos SET titulo_es = 'Truvani Proteína en Polvo Orgánica de Origen Vegetal | Vainilla | 18 porciones | Vegana | 20 g de proteína de guisante | Keto | Sin gluten y sin lácteos | Baja en carbohidratos | Sin azúcar añadido', descripcion_es = 'Truvani Proteína en Polvo Orgánica de Origen Vegetal | Vainilla | 18 porciones | Vegana | 20 g de proteína de guisante | Keto | Sin gluten y sin lácteos | Baja en carbohidratos | Sin azúcar añadido' WHERE asin = 'B0DDQHLWFN';

UPDATE productos SET titulo_es = 'ALOHA Barras de Proteína Orgánicas de Origen Vegetal - Barra de Mantequilla de Maní - 12 barras, veganas, bajas en azúcar, sin gluten, bajas en carbohidratos, sin OGM, sin stevia, sin eritritol', descripcion_es = 'ALOHA Barras de Proteína Orgánicas de Origen Vegetal - Barra de Mantequilla de Maní - 12 barras, veganas, bajas en azúcar, sin gluten, bajas en carbohidratos, sin OGM, sin stevia, sin eritritol' WHERE asin = 'B08ZVHH13J';